"""
Export Module
Handles export and documentation of results
"""

import streamlit as st
import pandas as pd
import json
from datetime import datetime


def render():
    """Render the Export panel"""
    st.markdown("<div class='ust-eyebrow'>Step 6: Documentation</div>", unsafe_allow_html=True)
    st.markdown("## Export & Share Results")

    if not st.session_state.analysis_complete:
        st.markdown("""
        <div class='ust-info-box'>
            <strong>⚠️ Analysis Required</strong><br>
            Complete the analysis to generate exportable reports.
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown("""
        <div class='ust-info-box'>
            <strong>Share your impact.</strong><br>
            Download comprehensive reports and executive summaries for stakeholder presentations.
        </div>
        """, unsafe_allow_html=True)

        # Compile report
        final_report = {
            'analysis_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'metadata': st.session_state.metadata,
            'quality_score': st.session_state.get('quality_report', {}).get('quality_score', 0),
            'purchase_scenario': st.session_state.dynamics_results['scenario']['scenario'],
            'best_channel': max(
                st.session_state.hte_results['channel_effects'].items(),
                key=lambda x: x[1]['pct_lift']
            )[0],
            'long_term_roi': st.session_state.roi_results['long_term']['roi_pct']
        }

        col1, col2 = st.columns(2)

        with col1:
            json_str = json.dumps(final_report, indent=2, default=str)
            st.download_button(
                label="📥 Download Full Report (JSON)",
                data=json_str,
                file_name=f"brightline_analysis_{datetime.now().strftime('%Y%m%d')}.json",
                mime="application/json",
                use_container_width=True
            )

        with col2:
            csv_data = pd.DataFrame([final_report])
            csv = csv_data.to_csv(index=False)
            st.download_button(
                label="📥 Download Summary (CSV)",
                data=csv,
                file_name=f"brightline_summary_{datetime.now().strftime('%Y%m%d')}.csv",
                mime="text/csv",
                use_container_width=True
            )

        st.markdown("---")

        # Executive Summary
        st.markdown("### 📋 Executive Summary")

        st.markdown(f"""
        ### Brightline RCT Incrementality Analysis
        **Analysis Date:** {datetime.now().strftime('%B %d, %Y')}

        #### 🎯 Key Findings

        **Purchase Behavior:** {st.session_state.dynamics_results['scenario']['scenario']}
        - {st.session_state.dynamics_results['scenario']['description']}

        **Best Channel:** {final_report['best_channel']}
        - Highest treatment effect across all retail channels

        **ROI Performance:**
        - Long-term ROI: **{st.session_state.roi_results['long_term']['roi_pct']:.1f}%**
        - Includes customer lifetime value contributions

        ---

        *Generated by UST Digital Transformation • Brightline RCT Framework*
        """)
